---
- name: Install Docker
  hosts: ansible_nodes
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == 'Debian'
      become: yes
      vars:
        ansible_ssh_private_key_file: /home/nishant/.ssh/id_rsa


    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

